### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by adarshme**
Added CONTRIBUTING.md.

I'll update #51 to link the CONTRIBUTING.md file.

### CODE REVIEW

**Comment by Animesh-Ghosh** [comment]
I suggest you update the **`README.md`** in this PR itself, unless it's for Hacktoberfest.

**Comment by adarshme** [comment]
I've updated README.md. I'm done with this year's Hacktoberfest.

**Review by Animesh-Ghosh — APPROVED** [review]
Nice job!

Thanks for the updated **`README.md`** and a new **`CONTRIBUTING.md`**.

**Comment by adarshme** [comment]
You're welcome 😄

**Comment by Animesh-Ghosh** [comment]
@InfernoCoder11 are you in BitsPlease society?

**Comment by adarshme** [comment]
Nope

**Comment by Animesh-Ghosh** [comment]
Ah. This repository was meant as a way for people in our society to practice competitive programming, but since it was created around 2 years ago it has not seen a lot of submissions.

Thanks for showing interest! 😅

**Pull request merged**
