### PR TITLE
solution to problem 25 and 26

### PR DESCRIPTION
**Pull request by Pranav-Khurana**
added 25.cpp, print arrow pattern and 26.cpp, print pattern 2, also removed unused variale i from 12.cpp

### CODE REVIEW

**Comment by amitbansal7** [comment]
This branch has conflicts that must be resolved
Use the web editor or the command line to resolve conflicts.
Ps. Avoid using conio.h & getch()

**Comment by Pranav-Khurana** [comment]
there's no use of conio.h and getch() in any of the two programs above, i removed them before adding to github, its showing the git commit of removing them and  conflict is resloved

**Comment by Pranav-Khurana** [comment]
actually, you r seeing conio.h and getch() in 25.cpp in this commit https://github.com/BitsPleaseMSI/BitsPlease-solutions/pull/10/commits/6c12d2197d3bb6224ecd2fc25f3bfe69aa0a54e1 which i removed when i added 26.cpp in this commit https://github.com/BitsPleaseMSI/BitsPlease-solutions/pull/10/commits/872072c2d3af31af13d993d2308d211586e4198a, this is causing misunderstanding.

**Comment by Pranav-Khurana** [comment]
Sorry but probably conflict is not solved yet, I'm not understanding how to solve it, plz guide me how to do this

**Comment by amitbansal7** [comment]
you need to pull changes first.. then after commit your changes.

**Pull request merged**
