### PR TITLE
Bits Please Solutions

### PR DESCRIPTION
**Pull request by Bhupesh-V**
Solutions to Problems 7 an d29

### CODE REVIEW

**Comment by amitbansal7** [comment]
Problem 7:
Solution is too slow. As numbers can be big.
Consider this test case
1
1000 100000000
Your code will take hours to print the output.
It will take O(n) for every number between 1000 and 100000000.
Try to improve this solution.
[Hint : use primality testing or sieve of Eratosthenes to check for primes]

Problem 29:
Your solution will overflow "long long int"
for input :
1
65
[Hint : Store number as strings]

**Comment by Bhupesh-V** [comment]
Thanks for suggestions !!
But storing numbers as string cannot be the only Solution ???

**Comment by amitbansal7** [comment]
Using Python can be one solution as variable size in python is only limited by memory available.
I think for C, C++, Java etc. storing huge numbers as integer arrays is the only solution.

**Comment by amitbansal7** [comment]
There are wrong solutions already uploaded under this pull request which cant be merged.
Send a different pull request for each problem.

**Pull request closed without merging**
