### PR TITLE
added solution to problem 21

### PR DESCRIPTION
**Pull request by Pranav-Khurana**

### CODE REVIEW

**Comment by sreejeet** [comment]
INCORRECT SOLUTION.
input: 
1
5
1 2 3 4 4
your output:
0 1 2 3 4
expected output:
0 1 2 3 1

**Comment by Pranav-Khurana** [comment]
is it correct now

**Comment by sreejeet** [comment]
Still incorrect for yet another test case. Read the question carefully.
For towers A and B to communicate, there should be no tower in between that has height equal or greater than the height of the tower on the right side.

**Comment by Pranav-Khurana** [comment]
this one must satisfy all the cases

**Comment by sreejeet** [comment]
You did it! :)

**Pull request merged**
