### PR TITLE
Problem solution to Problem 7

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**
Added a solution to Problem 7.

### CODE REVIEW

**Comment by amitbansal7** [comment]
Your solution to this problem is too slow.
Try : https://en.wikipedia.org/wiki/Primality_test
And send 1 pull request for 1 problem.

**Comment by Animesh-Ghosh** [comment]
Yeah. Sorry.

**Comment by amitbansal7** [comment]
Problem 8: You don't know where middle node is. You need to find it first.
You can't simply go to "9/2"th location.

**Comment by Animesh-Ghosh** [comment]
Will it help the execution time if I store the first 100 prime numbers and if one number isn't divisible by any of them (when the number is > 100 of course) then I decide it's prime as well?

**Comment by amitbansal7** [comment]
"if one number isn't divisible by any of them (when the number is > 100 of course) then I decide it's prime as well" I am not sure if this is going to work.
Try: sieve of Eratosthenes or https://en.wikipedia.org/wiki/Primality_test

**Comment by Animesh-Ghosh** [comment]
image
Is this what you are suggesting I should implement?

**Comment by amitbansal7** [comment]
Yes.

**Pull request closed without merging**
