### PR TITLE
Solutions for Problems: 1, 2, 3; Animesh Ghosh

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**
New pull request with solutions to problems 1, 2, 3.

### CODE REVIEW

**Comment by sreejeet** [comment]
Solutions 2 and 3 are incorrect. You can make solution 2 more efficient. (Hint: use euler gcd algorithm)

Please send **only one pull request per solution**.

**Comment by Animesh-Ghosh** [comment]
I agree that solution 3 is incorrect since I misunderstood the question, but solution 2 does work. Even if it's O^2 order (I think). Please add it as an alternate solution, easier to understand.

**Comment by amitbansal7** [comment]
Time complexity of your solution of problem 2 is O(max(a, b)).
And it doesn't work
10 10
ans is:10
your code gives: 5

**Comment by Animesh-Ghosh** [comment]
Have updated the problem. Still don't know how to do 3rd problem. Euclid's algorithm for the GCD problem will be implemented afterwards, since I don't fully understand it.

**Pull request closed without merging**
