### PR TITLE
Update 10.cpp

### PR DESCRIPTION
**Pull request by adarshme**
Better solution with meaningful variable names and documentation

### CODE REVIEW

**Comment by Animesh-Ghosh** [comment]
Hi!

I just saw that you created this **PR from your master** branch. That's **not** how you contribute in Open Source projects.

1. You need to ***create a separate branch*** for your changes.
2. **Make changes** in that branch.
3. **Push** your branch **to remote (that is, to GitHub).**
4. Then **create a Pull Request** from the remote branch.

Hope you understand. Let me know if there's any doubt.

**Comment by adarshme** [comment]
All right, I'll make a new pull request with the requirements in mind. I suggest you to mention these requirements in the readme so that newcomers know how they're supposed to contribute to this project.

**Comment by Animesh-Ghosh** [comment]
Why don't you create a PR for it? 😉

**Comment by InfernoCoder11** [comment]
Actually, I did.
Its this one #50.

**Comment by adarshme** [comment]
Will do 👍 

Edit - Here's the update readme PR - #51

**Pull request closed without merging**
