### PR TITLE
Update 26.cpp

### PR DESCRIPTION
**Pull request by John-Weak**
Less complex.
Need help to compare O(n).

### CODE REVIEW

**Comment by John-Weak** [comment]
Since an odd no. example was not given in the question,it resulted in 2 possibilties:
1. inversed pointed arrow (pattern formed by *)
2. inversed blunt arrow
My code outputs option 1,but if option 2 is acceptable deleting line 12,14,15 results in option 2 resulting in even smaller code.

**Review by Pranav-Khurana — COMMENTED** [review]
The new code is fine and less complex and mergeable, although as @John-Weak said, there are no examples for odd inputs and if the output of odd numbers should be as same as of even numbers, then code doesn't give desired output and is not mergeable.

**Comment by Animesh-Ghosh** [comment]
@John-Weak take it as the inverse pointed arrow:
```
\   |   /
 \  |  /
  \ | /
```

**Comment by John-Weak** [comment]
> @John-Weak take it as the inverse pointed arrow:
> 
> ```
> \   |   /
>  \  |  /
>   \ | /
> ```

u mean 2nd option???(the pattern displayed by even no. inputs)

**Comment by Animesh-Ghosh** [comment]
It is possible. No need to make it less complex than O(n<sup>2</sup>) since printing that pattern requires a double for loop.

EDIT:
A much more simpler approach exists. Something to do with the index that the asterisks need to be printed at.

**Comment by John-Weak** [comment]
code updated to output patterns as followed by even numbers.

**Review by Animesh-Ghosh — APPROVED** [review]
This is good. Although I would have just taken the asterisk indexes in an array and compared the inner j index with each of the index where '*' is supposed to be printed, and then modified the  0<sup>th</sup> and 2<sup>nd</sup> index of the array for each iteration of the outer loop.

**Pull request merged**
