### PR TITLE
Created 8.c

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**
Using counter variable to find middle node and then deleting after linking using '->' operator.

Have some doubts in the question like what exactly did it mean to **"complete in 1 pass"** .

### CODE REVIEW

**Comment by sreejeet** [comment]
"complete in 1 pass" means you should only traverse the entire linked list once. In your code, you traverse the entire list [Line: 33], and then again traverse half of it [Line: 38].
There is a way to do it in just one traversal of the list... think about it.

**Comment by amitbansal7** [comment]
This solution is good enough for the time being. We can merge this. But we are expecting an update to this solution with single pass algorithm.

**Comment by Animesh-Ghosh** [comment]
Sure. I'll think about it. But you've gotta give me some hints at least BD.

**Comment by amitbansal7** [comment]
Traverse using a "slow" pointer and a "fast" pointer. slow pointer takes 1 step at a time and fast pointer takes two steps. Move them simultaneously. When fast pointer reaches end.. slow will be in the middle.

**Pull request merged**
