### PR TITLE
added Print Primes(Id 7) by Pranav

### PR DESCRIPTION
**Pull request by Pranav-Khurana**

### CODE REVIEW

**Comment by amitbansal7** [comment]
Hey! 
This code works but only for small inputs..
As value of x and y increases say 100 - 1000000 your code will take huge amount of time.
Your code uses Brute Force approach to check for primes which takes O(n) time, and it is too slow.
So try to improve the time complexity of checking for primes.
There are very fast algorithms available out there. like https://en.wikipedia.org/wiki/Primality_test
Improve this solution.. and send a pull request again 💯 
PS: Avoid conio.h

**Comment by Pranav-Khurana** [comment]
Ok Thanks, i'll work on it and try to improve it. Also i have tried id 10 (Sum the array digits), also see that and tell me how can i improve that

**Comment by amitbansal7** [comment]
Hey!
What if numbers are 20 digits long?
Value of v1 and v2 will overflow.
Add the numbers within an array only.
While writing solutions you should always take care of large inputs.

**Comment by Pranav-Khurana** [comment]
hey, 
I modified the 10th problem, hope this time it is upto your requirements. Also i want to ask that can i try 7th (print primes) in python.

**Comment by amitbansal7** [comment]
Hey,
(problem 10)your code fails on this test case:
2
9 9
2
3 4

yes, you can try problems in any programming language.

**Comment by Pranav-Khurana** [comment]
sry, i forgot to include this case where the arrays of n size and there sum is of n+1 size, now it's there, i modified it

**Comment by Pranav-Khurana** [comment]
Sry, third case (where arrays are of size n and sum is of size n+1)  wasn't included. Now it is included.

**Comment by amitbansal7** [comment]
So now it works.. but don't you think that your code is little messed up(not readable at all).
These solutions are for real people to read. Those who are not able to solve  problems by themselves can take a look at your code.
replace your code with formatted version of same code(https://ideone.com/lfpxPF) and remember to format your code properly next time.
I would have done it for you.. but then code wouldn't belong to you.

**Pull request merged**
