### PR TITLE
BitsPlease solution

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**
Uploaded solution for problem 7 at http://bitsplease.pythonanywhere.com.

### CODE REVIEW

**Comment by amitbansal7** [comment]
Time complexity is ok.
But this can be solved using O(1) space.
Checkout primality testing.
and it gives "Segmentation fault: 11", even on not so large inputs.
1
1 100000

Still merging it.

**Comment by Animesh-Ghosh** [comment]
The max upper limit that I could enter was 46348. I have implemented Eratosthenes' Sieve which specifically says to list out the consecutive numbers. Constant space in this case is not possible IMO. Are you referring to some other algorithm? 

Correct me if I'm wrong about Segmentation fault, but what I understand from it is that it occurs when array index is out of bounds. 

100000 means 100000 * sizeof (int). Assuming 2 bytes for integer data type, that would mean almost 200 MB which is greater than the 64 MB memory given on many online IDEs. So, I wouldn't say 100000 is a small input. However, I do agree that it should be able to handle atleast upto that number.

EDIT: 
Which debugger are you using? I'm using the one included with Dev-Cpp which is GDB. It gave the same error and then showed me some stuff which really didn't understand. Will post the image soon. Hope to get some insight.

Here is the window:
image
The error message was SIGSEGV specifically.

Thanks for merging it anyway.

**Comment by amitbansal7** [comment]
You could use primality testing [checkout this solution](https://github.com/amitbansal7/Competitive-Programming/blob/master/SPOJ/PRIME1.c) this uses constant space.
PS. 100000 ints is 0.4MB not 200 MB.

**Comment by Animesh-Ghosh** [comment]
This is a different algorithm bases on characteristics/observations of numbers. I have implemented Eratosthenes' Sieve; it works but now I know it's limitations.

I wracked my brain but I couldn't understand how 100000 ints (as in an int array of size 100000) is 0.4 MB.

PS:- in your program you can even further optimize by doing the following:
```cpp
while(i*i<=sqrt(n))
```
EDIT:
I don't know if it will affect the performance in any way, but why not give it a try?
EDIT 2:
Scratch that. It seems to work well, until you reach an edge case such as 999997, which is not prime. 

Thanks for the feedback.

**Comment by amitbansal7** [comment]
check [this](https://ideone.com/aPmWGg).
"while(i*i<=sqrt(n))" this is wrong. [primality testing](https://en.wikipedia.org/wiki/Primality_test)

**Comment by Animesh-Ghosh** [comment]
I see. My brain kept going to MB directly from bytes. I forgot about KBs. I would like to know why sqrt(n) in the while condition does not work. I guess it just doesn't work. But thanks for accommodating me.

**Pull request merged**
