### PR TITLE
Updated 8.c

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**
Please resolve the merge issue.

### CODE REVIEW

**Comment by amitbansal7** [comment]
File name should be 8.cpp
Ps. There is a bug on line 35.

**Comment by Animesh-Ghosh** [comment]
image
Changed the name of the file to .cpp.
Where is the bug? Linking seems fine to me. Any syntax errors?

**Comment by amitbansal7** [comment]
Did you test this?

**Comment by Animesh-Ghosh** [comment]
No. I didn't. Cuz I'm using the web platform.

**Comment by amitbansal7** [comment]
I think you should test this on your machine.

**Pull request closed without merging**
